const ERROR_MESSAGE = {
	NAME_EMPTY:'Name can\'t be empty.',
	EMAIL_EMPTY:'Email can\'t be empty.',
	PASSWORD_EMPTY:'Password can\'t be empty.',
	USER_ALREADY_EXIST:'User already exist.',
	USER_DOES_NOT_EXIST:'User doesn\'t exist.',
	NO_DATA:'No Data Found',
	INVALID_PASSWORD: 'Invalid password.',
	INVALID_CREDITS: 'Invalid credentials.',
	INVALID_OTP: 'Invalid or expired OTP',
	EMAIL_INCORRECT:'Email is incorrect.',
	SOMETING_WENT_WRONG: 'Someting went wrong, try again!',
	SOMETING_WENT_WRONG_ZOHO: 'Someting went wrong, while generating access token!',
	NO_EMAIL_IN_HEADER: 'No email provided.',
	NO_ACCESS: 'You do not have access to this portal.',
	NO_TOKEN_IN_HEADER: 'No token provided.',
	AUTHENTICATION_FAILED: 'Authentication failed.',
	SERVICE_UNAVAILABLE: 'Currently service is unavailable.',
	INVALID_UPDATED_TOKEN: 'Invalid updated token.',
	UPDATE_PASSWORD_TOKEN_EXPIRED: 'Token has been expired.',
	TOKEN_GENERATION_FAILED: 'Token generation failed, Please contact admin.',
	SOMETHING_WENT_WRONG: 'Something went wrong!!!, Please contact admin.',
	QUERYEXECUTE: 'Query execution error, Please contact admin.',
	MOREACCOUNTS: 'We have found that more than one account is associated with the email address provided. To proceed, could you please provide the account number corresponding to the email?',
	NOACCOUNTS: "I'm sorry, We didn't find an account that contains that email. Please provide an account number",
	FILEGENERATION: "File generation error, Please contact admin.",
};
module.exports = ERROR_MESSAGE;